//! Autogenerated weights for evm
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 2.0.0
//! DATE: 2021-01-04, STEPS: [1, ], REPEAT: 1, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB
//! CACHE: 128

#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::weights::{constants::RocksDbWeight as DbWeight, Weight};

/// Weight functions for evm.
impl crate::WeightInfo for () {
    fn transfer_maintainer() -> Weight {
        Weight::from_parts(249_253_000, 0)
            .saturating_add(DbWeight::get().reads(4 as u64))
            .saturating_add(DbWeight::get().writes(2 as u64))
    }
    fn deploy() -> Weight {
        Weight::from_parts(359_916_000, 0)
            .saturating_add(DbWeight::get().reads(4 as u64))
            .saturating_add(DbWeight::get().writes(3 as u64))
    }
    fn deploy_free() -> Weight {
        Weight::from_parts(79_203_000, 0)
            .saturating_add(DbWeight::get().reads(1 as u64))
            .saturating_add(DbWeight::get().writes(1 as u64))
    }
    fn enable_contract_development() -> Weight {
        Weight::from_parts(221_257_000, 0)
            .saturating_add(DbWeight::get().reads(3 as u64))
            .saturating_add(DbWeight::get().writes(2 as u64))
    }
    fn disable_contract_development() -> Weight {
        Weight::from_parts(215_920_000, 0)
            .saturating_add(DbWeight::get().reads(3 as u64))
            .saturating_add(DbWeight::get().writes(2 as u64))
    }
    fn set_code() -> Weight {
        Weight::from_parts(238_383_000, 0)
            .saturating_add(DbWeight::get().reads(4 as u64))
            .saturating_add(DbWeight::get().writes(3 as u64))
    }
    fn selfdestruct() -> Weight {
        Weight::from_parts(544_511_000, 0)
            .saturating_add(DbWeight::get().reads(7 as u64))
            .saturating_add(DbWeight::get().writes(5 as u64))
    }
}
