//! Autogenerated weights for module_poc
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-04-07, STEPS: [50, ], REPEAT: 20, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/reef-node
// benchmark
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=module_poc
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./modules/poc/src/weights.rs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for module_poc.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
    fn on_initialize_empty() -> Weight {
        Weight::from_parts(19_557_000, 0)
            .saturating_add(T::DbWeight::get().reads(2 as u64))
            .saturating_add(T::DbWeight::get().writes(1 as u64))
    }
    fn on_initialize_era(_c: u32) -> Weight {
        Weight::from_parts(21_538_473_000, 0)
            // Standard Error: 27_000
            // .saturating_add((63_000 as u64).into())
            .saturating_add(T::DbWeight::get().reads(2025 as u64))
            .saturating_add(T::DbWeight::get().writes(25 as u64))
    }
    fn start_candidacy() -> Weight {
        Weight::from_parts(66_356_000, 0)
            .saturating_add(T::DbWeight::get().reads(3 as u64))
            .saturating_add(T::DbWeight::get().writes(3 as u64))
    }
    fn stop_candidacy() -> Weight {
        Weight::from_parts(77_247_000, 0)
            .saturating_add(T::DbWeight::get().reads(4 as u64))
            .saturating_add(T::DbWeight::get().writes(3 as u64))
    }
    fn commit() -> Weight {
        Weight::from_parts(65_845_000, 0)
            .saturating_add(T::DbWeight::get().reads(3 as u64))
            .saturating_add(T::DbWeight::get().writes(3 as u64))
    }
    fn add_funds() -> Weight {
        Weight::from_parts(70_473_000, 0)
            .saturating_add(T::DbWeight::get().reads(3 as u64))
            .saturating_add(T::DbWeight::get().writes(3 as u64))
    }
    fn unbond() -> Weight {
        Weight::from_parts(40_417_000, 0)
            .saturating_add(T::DbWeight::get().reads(1 as u64))
            .saturating_add(T::DbWeight::get().writes(1 as u64))
    }
    fn withdraw() -> Weight {
        Weight::from_parts(68_720_000, 0)
            .saturating_add(T::DbWeight::get().reads(3 as u64))
            .saturating_add(T::DbWeight::get().writes(3 as u64))
    }
    fn vote_candidate() -> Weight {
        Weight::from_parts(87_216_000, 0)
            .saturating_add(T::DbWeight::get().reads(4 as u64))
            .saturating_add(T::DbWeight::get().writes(3 as u64))
    }
}

use frame_support::weights::constants::RocksDbWeight as DbWeight;
impl crate::WeightInfo for () {
    fn on_initialize_empty() -> Weight {
        Weight::from_parts(19_557_000, 0)
            .saturating_add(DbWeight::get().reads(2 as u64))
            .saturating_add(DbWeight::get().writes(1 as u64))
    }
    fn on_initialize_era(_c: u32) -> Weight {
        Weight::from_parts(21_538_473_000, 0)
            // Standard Error: 27_000
            // .saturating_add((63_000 as u64).into())
            .saturating_add(DbWeight::get().reads(2025 as u64))
            .saturating_add(DbWeight::get().writes(25 as u64))
    }
    fn start_candidacy() -> Weight {
        Weight::from_parts(66_356_000, 0)
            .saturating_add(DbWeight::get().reads(3 as u64))
            .saturating_add(DbWeight::get().writes(3 as u64))
    }
    fn stop_candidacy() -> Weight {
        Weight::from_parts(77_247_000, 0)
            .saturating_add(DbWeight::get().reads(4 as u64))
            .saturating_add(DbWeight::get().writes(3 as u64))
    }
    fn commit() -> Weight {
        Weight::from_parts(65_845_000, 0)
            .saturating_add(DbWeight::get().reads(3 as u64))
            .saturating_add(DbWeight::get().writes(3 as u64))
    }
    fn add_funds() -> Weight {
        Weight::from_parts(70_473_000, 0)
            .saturating_add(DbWeight::get().reads(3 as u64))
            .saturating_add(DbWeight::get().writes(3 as u64))
    }
    fn unbond() -> Weight {
        Weight::from_parts(40_417_000, 0)
            .saturating_add(DbWeight::get().reads(1 as u64))
            .saturating_add(DbWeight::get().writes(1 as u64))
    }
    fn withdraw() -> Weight {
        Weight::from_parts(68_720_000, 0)
            .saturating_add(DbWeight::get().reads(3 as u64))
            .saturating_add(DbWeight::get().writes(3 as u64))
    }
    fn vote_candidate() -> Weight {
        Weight::from_parts(87_216_000, 0)
            .saturating_add(DbWeight::get().reads(4 as u64))
            .saturating_add(DbWeight::get().writes(3 as u64))
    }
}
