[package]
authors = ['Reef <https://reef.io>']
build = 'build.rs'
description = 'Reef Node'
edition = '2021'
homepage = 'https://reef.io'
license = 'Unlicense'
name = 'reef-node'
repository = 'https://github.com/reef-defi/reef-chain'
version = '4.0.0'

[[bin]]
name = 'reef-node'

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }

[dependencies]
hex-literal = "0.3.1"
jsonrpc-core = '15.1.0'
structopt = '0.3.8'
clap = { version = "4.2.5", features = ["derive"] }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
jsonrpsee = { version = "0.16.2", features = ["server"] }
futures = { version = "0.3.21", features = ["thread-pool"]}

# Substrate dependencies
frame-benchmarking = { workspace = true ,default-features = false }
frame-benchmarking-cli = { workspace = true ,default-features = false }
pallet-transaction-payment-rpc = { workspace = true ,default-features = false }
sc-chain-spec=  { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-basic-authorship = { workspace = true ,default-features = false }
sc-cli =  { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-client-api =  { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-rpc-api=  { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-transaction-pool = { workspace = true ,default-features = false }
sc-transaction-pool-api = { workspace = true ,default-features = false }
sc-telemetry = { workspace = true ,default-features = false }
sp-std = { workspace = true ,default-features = false }
sp-api = { workspace = true ,default-features = false }
sp-block-builder = { workspace = true ,default-features = false }
sp-blockchain = { workspace = true ,default-features = false }
sp-core  = { workspace = true ,default-features = false }
sp-inherents = { workspace = true ,default-features = false }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-runtime  = { workspace = true ,default-features = false }
sp-transaction-pool  = { workspace = true ,default-features = false }
sp-timestamp = { workspace = true ,default-features = false }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }

sc-keystore = { workspace = true ,default-features = false }
sp-keystore = { workspace = true ,default-features = false }
# sp-finality-grandpa = { workspace = true ,default-features = false }
grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43",package = "sc-consensus-grandpa"}
sc-consensus-grandpa-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }

sp-consensus = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-consensus-grandpa = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" ,default-features=false }
sc-consensus = { workspace = true }
sc-consensus-babe = { workspace = true ,default-features = false }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-keyring = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" ,default-features=false }
frame-system = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" ,default-features=false }
pallet-transaction-payment = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" ,default-features=false }
# sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sc-consensus-slots = {workspace = true,default-features = false}

# kitchensink-runtime = { workspace = true ,default-features = false }

module-evm = { path = "../modules/evm" }
# module-evm-rpc-runtime-api = { path = "../modules/evm/rpc/runtime_api" }
evm-rpc = { path = "../modules/evm/rpc" }

reef-primitives = { path = "../primitives" }

# runtime
reef-runtime = { path = '../runtime', version = '4.0.0' }

[features]
default = []
# runtime-benchmarks = ['reef-runtime/runtime-benchmarks', 'kitchensink-runtime/runtime-benchmarks']
with-ethereum-compatibility = [
	"reef-runtime/with-ethereum-compatibility"
]